#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# $Log: not supported by cvs2svn $
#
#

CMPLR = ANSI

#RATIONAL = purify
#RATIONAL = quantify
#RATIONAL = purecov
ifdef RATIONAL
HOST_OPT = NO
CC := $(RATIONAL) -best-effort $(CC)
CCC := $(RATIONAL) -best-effort $(CCC)
endif

LIBRARY = SDDSpp

USR_CXXFLAGS = -std=c++17 -I../../include -DEXPORT_SDDSPP -DzLib

LIB_SRCS = SDDSModern.cc \
           SDDSLayout.cc \
           SDDSIO.cc \
           SDDSTransform.cc \
           SDDSLegacy.cc

USR_LIBS_WIN32 += z
LIB_SYS_LIBS_DEFAULT = z lzma
LIB_SYS_LIBS_WIN32 = -nil-

z_DIR = $(INSTALL_LIB)
