include ../Makefile.rules

INC = SDDS.h \
      SDDStypes.h \
      constants.h \
      contour.h \
      fftpackC.h \
      hashtab.h \
      lookupa.h \
      match_string.h \
      matlib.h \
      mdb.h \
      namelist.h \
      non_dominated_sort.h \
      recycle.h \
      rpn.h \
      scan.h \
      standard.h \
      table.h
      
include ../Makefile.build

